CREATE TABLE People(Id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,  First VARCHAR(255), Last VARCHAR(255)); 
CREATE TABLE PhoneNumbers(Id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, PersonId int REFERENCES People (Id) ON DELETE CASCADE NOT NULL, PhoneTypeId int REFERENCES PhoneTypes NOT NULL, Number bigint NOT NULL);
CREATE TABLE PhoneTypes(Id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, Type VARCHAR(10) NOT NULL);
CREATE UNIQUE INDEX "People_Id_Idx" ON "People"( "Id" );
CREATE UNIQUE INDEX "PhoneNumbers_Id_Idx" ON "PhoneNumbers"( "Id" );
INSERT INTO PhoneTypes(Type) values("Cell");
INSERT INTO PhoneTypes(Type) values("Work");
INSERT INTO PhoneTypes(Type) values("Home");
